#!/usr/bin/env bash
# main : () -> string
# Create a file that is only executable. Return the path to the file.
function main {
	local -r tmp=$(mktemp --directory) || return 1
	local -r file="$tmp/executable-file" || return 1
	touch "$file" || return 1
	chmod ugo-srwx "$file" || return 1
	chmod ugo+x "$file" || return 1
	echo "$file" || return 1
	return 0
}

main "$@"
