#!/usr/bin/env bash
# main : () -> string
# Create a file with the set-user-ID bit set. Return the path to the file.
function main {
	local -r tmp=$(mktemp --directory) || return 1
	local -r file="$tmp/file-with-set-user-id" || return 1
	touch "$file" || return 1
	chmod ugo-srwx "$file" || return 1
	chmod u+s "$file" || return 1
	echo "$file" || return 1
	return 0
}

main "$@"
