#!/usr/bin/env bash
# main : () -> string
# Create a file with the set-group-ID bit set. Return the path to this file.
function main {
	local -r tmp=$(mktemp --directory) || return 1
	local -r file="$tmp/file-with-set-group-id" || return 1
	touch "$file" || return 1
	chmod ugo-srwx "$file" || return 1
	chmod g+s "$file" || return 1
	echo "$file" || return 1
	return 0
}

main "$@"
