#!/usr/bin/env bash
# main: () -> string
# Create a directory. Return the path to the directory.
function main {
	local -r tmp=$(mktemp --directory) || return 1
	local -r directory="$tmp/directory" || return 1
	mkdir "$directory" || return 1
	echo "$directory" || return 1
	return 0
}

main "$@"
