#!/usr/bin/env bash
# main : () -> string
# Create a file. Return the path to the file.
function main {
	local -r tmp=$(mktemp --directory) || return 1
	local -r file="$tmp/nonempty-file" || return 1
	echo "This file is not empty." > "$file" || return 1
	chmod ugo-srwx "$file" || return 1
	echo "$file" || return 1
	return 0
}

main "$@"
